DROP TABLE IF EXISTS  payment;
DROP TABLE IF EXISTS  patient_oral_examination;
DROP TABLE IF EXISTS  default_oral_examination;
DROP TABLE IF EXISTS  treatment;
DROP TABLE IF EXISTS  status;
DROP TABLE IF EXISTS  doctor_patient_mapping;
DROP TABLE IF EXISTS  user_detail;
DROP TABLE IF EXISTS  user_credentials;
DROP TABLE IF EXISTS  role;
