DROP TABLE payment;
DROP TABLE patient_oral_examination;
DROP TABLE default_oral_examination;
DROP TABLE treatment;
DROP TABLE status;
DROP TABLE doctor_patient_mapping;
DROP TABLE user_detail;
DROP TABLE user_credentials;
DROP TABLE role;
